steps:

 # install dependencies for angular app

 - name: "gcr.io/cloud-builders/npm"

   args: ["install"]


 # build production ready frontend angular app

 - name: "gcr.io/cloud-builders/npm"

   args: [run, ng, "--", build, "--prod"]


 # OPTIONALLY remove current/old files


 # upload newly pushed files (for frontend)

 - name: "gcr.io/cloud-builders/gcloud"

   args:

    [

     "compute",

     "scp",

     "--recurse",

     "dist",

     "la-test-angular-node-1:/var/",

     "--zone=us-central1-a",

   ]





 
