steps:

  # Install node packages
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'install' ]

  # Build productive files
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'run', 'build', '--prod' ]
    
  - name: "gcr.io/cloud-builders/gcloud"

   args:

    [

     "compute",

     "scp",

     "--recurse",

     "dist",

     "la-test-angular-node-1:/var/",

     "--zone=us-central1-a",

   ]
