steps:
# Install
- name: 'gcr.io/cloud-builders/npm:node-14.15.0'
  args: ['install']
# Build
- name: 'gcr.io/cloud-builders/npm-14.15.0'
  args: ['run', 'build']
 
- name: "gcr.io/cloud-builders/gcloud"
  args: [ 'compute' , 'scp' , '--recursive' , 'dist' , 'la-test-angular-node-1:/var/' , '--zone=us-central1-a' ]


#steps:

  # Install node packages
 # - name: 'gcr.io/cloud-builders/npm'
  #  args: [ 'install' ]

  # Build productive files
#  - name: 'gcr.io/cloud-builders/npm'
#    args: [ 'run', 'build', '--prod' ]
    
#  - name: "gcr.io/cloud-builders/gcloud"
#    args: [ 'compute' , 'scp' , '--recursive' , 'dist' , 'la-test-angular-node-1:/var/' , '--zone=us-central1-a' ]

 
